# fly.toml file generated for ancient-dew-2472 on 2021-08-31T16:16:57+07:00

app = "ancient-dew-2472"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
